# ~/.tmuxinator/filib-blog.yml

name: filib-blog
root: ~/Projects/personal/mcfilib.github.io

on_project_start: git checkout develop
windows:
  - editor:
      ec .
  - compiler:
      layout: even-vertical
      panes:
        - stack install --fast --file-watch
        - stack exec filib-io watch
        - git status
